data endpoint realization
kuzhukin/goph-keeper pull request #1
Opened 2024-04-06 19:57 UTC by kuzhukin

2024-06-12 18:54 UTC, tmvrus reviewed
- пакет fmt для логирования не предназначен
- большие файлы это признак плохого дизайна, усложняют сопровождение проекта
- sqlite вполе работает с контекстом, почему это не используется?
https://github.com/mattn/go-sqlite3/blob/master/sqlite3_go18.go#L27
- довольно странное обращение с транзакциями

2024-06-12 18:54 UTC, tmvrus commented on cmd/client/main.go
> +		fmt.Println("error:", err)
пакет fmt для логирования не предназначен

2024-06-12 18:54 UTC, tmvrus commented on internal/client/app.go
> +package client
752 строки, это перебор пожалуй, может разбить хоть как-то?

2024-06-12 18:54 UTC, tmvrus commented on internal/client/app.go
> +		if user != nil {
кака читать такое повидение?
может быть ошибка, но если sqlstorage.ErrNotActiveOrRegistredUsers то ок - работаем дальше
но user все еще может быть nil, но и это ок - работаем дальше

2024-06-12 18:54 UTC, tmvrus commented on internal/client/app.go
> +	value := ctx.String("value")
а может value как-то назвать разумно, что бы было понятно что там лежит

2024-06-12 18:54 UTC, tmvrus commented on internal/client/client.go
> +func doRequest(req *http.Request) (*http.Response, error) {
вот это ф-я выполняет реквест без явных ограничений, это так себе практика, обычно используют http.RequestWithContext либо явныи образом настраивают http.Client

2024-06-12 18:54 UTC, tmvrus commented on internal/client/config/config.go
> +	"github.com/kuzhukin/goph-keeper/internal/utils"
utils максимально неудачное название пакета, поскольку не говорит ничего конкретного о его содержимом, если нужен yml читатель отчего бы создать пакет сразу с названием формата

2024-06-12 18:54 UTC, tmvrus commented on internal/client/config/config.go
> +	DefaultAppDirName = ".goph-keeper"
это константа экспортируемая, хотя снаружи не используется

2024-06-12 18:54 UTC, tmvrus commented on internal/client/storage/sqlstorage/db.go
> +	tx, err := s.db.Begin()
зачем тут транзакция? какую проблему она решает

2024-06-12 18:54 UTC, tmvrus commented on internal/client/storage/sqlstorage/db.go
> +			fmt.Printf("db transaction panics with error: %v\n", panicErr)
и далее идет ролбек закомиченой транзакции, странно

2024-06-12 18:54 UTC, tmvrus commented on internal/client/storage/sqlstorage/db.go
> +		panicErr := recover()
а какой в этом смысл, если на ход программы это не влияет?

2024-06-12 18:54 UTC, tmvrus commented on internal/client/storage/sqlstorage/db.go
> +	}
я нельзя одно значение выбрать QueryRow?

2024-06-12 18:54 UTC, tmvrus commented on internal/client/storage/sqlstorage/db.go
> +	}
не или хелпер создать, в нескольких местах же такое

2024-06-12 18:54 UTC, tmvrus commented on internal/client/storage/sqlstorage/user_table_requests.go
> +		PRIMARY KEY ("login", "password")
ну такое себе, если пользователь меняет пароль то и ключ менять придется, обычно так не делают

2024-06-12 18:54 UTC, tmvrus commented on internal/server/sql/storage.go
> +	tx, err := c.db.BeginTx(ctx, nil)
а зачем тут транзакция?

2024-06-12 18:54 UTC, tmvrus commented on internal/server/sql/storage.go
> +	}
а почему нельзя просто UPDATE в базу послать с  условием where revision == ?, после проверить было обновление или нет

2024-06-16 15:58 UTC, kuzhukin commented on cmd/client/main.go
> +		fmt.Println("error:", err)
Так это и не логирование в журнал. Это вывод инфы для юзера. Я не хочу писать в стдаут строки с текущей датой и временем (или еще что то в этом роде). Пользователю это не нужно.
На сервере логи пишутся через 	"go.uber.org/zap"
На клиенте вывод инфы делается через fmt.

2024-06-16 17:08 UTC, kuzhukin commented on internal/client/app.go
> +package client
Разделил. Вынес обработчики в пакет action

2024-06-16 17:12 UTC, kuzhukin commented on internal/client/app.go
> +		if user != nil {
добавил коммент

2024-06-16 17:14 UTC, kuzhukin commented on internal/client/app.go
> +	value := ctx.String("value")
Там может лежать что угодно.
В качестве секрета храним любые пары типа ключ-значение

2024-06-16 17:21 UTC, kuzhukin commented on internal/client/client.go
> +func doRequest(req *http.Request) (*http.Response, error) {
добавил ctx в запрос

2024-06-16 17:26 UTC, kuzhukin commented on internal/client/config/config.go
> +	"github.com/kuzhukin/goph-keeper/internal/utils"
переименовал

2024-06-16 17:26 UTC, kuzhukin commented on internal/client/config/config.go
> +	DefaultAppDirName = ".goph-keeper"
поправил

2024-06-16 17:31 UTC, kuzhukin commented on internal/client/storage/sqlstorage/db.go
> +	tx, err := s.db.Begin()
можно убрать

2024-06-16 17:32 UTC, kuzhukin commented on internal/client/storage/sqlstorage/db.go
> +			fmt.Printf("db transaction panics with error: %v\n", panicErr)
убрал вместе с транзакцией

2024-06-16 17:32 UTC, kuzhukin commented on internal/client/storage/sqlstorage/db.go
> +		panicErr := recover()
убрал вместе с транзакцией

2024-06-16 17:33 UTC, kuzhukin commented on internal/client/storage/sqlstorage/db.go
> +	}
Можно было. Но по-моему и так как я написал можно.

2024-06-16 17:34 UTC, kuzhukin commented on internal/client/storage/sqlstorage/user_table_requests.go
> +		PRIMARY KEY ("login", "password")
убрал пароль из ключа

2024-06-16 17:37 UTC, kuzhukin commented on internal/server/sql/storage.go
> +	tx, err := c.db.BeginTx(ctx, nil)
чтоб атомарно получить юзера и выполнить над его данными какие то действие (в данном случае добавить данных). Кажется что можно делать это в двух разных запросах, но атомарно как то надежнее.

2024-06-16 17:38 UTC, kuzhukin commented on internal/server/sql/storage.go
> +	}
Наверное можно и так. Но я перед этим проверяю еще наличие изменений в данных и не пишу, если изменений нет.

2024-06-18 07:42 UTC, tmvrus requested changes
```
go test ./... -cover
	github.com/kuzhukin/goph-keeper/cmd/client		coverage: 0.0% of statements
?   	github.com/kuzhukin/goph-keeper/internal/client/storage	[no test files]
	github.com/kuzhukin/goph-keeper/cmd/server		coverage: 0.0% of statements
	github.com/kuzhukin/goph-keeper/internal/client/cli		coverage: 0.0% of statements
?   	github.com/kuzhukin/goph-keeper/internal/server/endpoint	[no test files]
	github.com/kuzhukin/goph-keeper/internal/client/cli/action		coverage: 0.0% of statements
	github.com/kuzhukin/goph-keeper/internal/client/config		coverage: 0.0% of statements
	github.com/kuzhukin/goph-keeper/internal/client/storage/sqlstorage		coverage: 0.0% of statements
	github.com/kuzhukin/goph-keeper/internal/client/transport		coverage: 0.0% of statements
	github.com/kuzhukin/goph-keeper/internal/server/config		coverage: 0.0% of statements
	github.com/kuzhukin/goph-keeper/internal/server		coverage: 0.0% of statements
	github.com/kuzhukin/goph-keeper/internal/server/middleware		coverage: 0.0% of statements
	github.com/kuzhukin/goph-keeper/internal/server/sql		coverage: 0.0% of statements
	github.com/kuzhukin/goph-keeper/internal/zlog		coverage: 0.0% of statements
	github.com/kuzhukin/goph-keeper/internal/yaml		coverage: 0.0% of statements
ok  	github.com/kuzhukin/goph-keeper/internal/client/cli/args	0.618s	coverage: 37.3% of statements
ok  	github.com/kuzhukin/goph-keeper/internal/client/gophcrypto	0.454s	coverage: 78.9% of statements
ok  	github.com/kuzhukin/goph-keeper/internal/server/handler	0.498s	coverage: 64.5% of statements
```
<img width="737" alt="image" src="https://github.com/kuzhukin/goph-keeper/assets/554425/a69702b4-42dc-4a05-a2f4-809598f76738">

2024-06-20 12:43 UTC, tmvrus approved these changes
Поздравляю

2024-06-20 14:04 UTC, merged